version: '3.7'

services:
  db:
    image: postgres:9.4
    container_name: risk_place_db
    tty: true
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - vam_mos
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  api:
    container_name: risk_place_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/go/src/
    ports:
      - "${PORT_SERVER}:${PORT_SERVER}"
    networks:
      - vam_mos
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  vam_mos: {}

volumes:
  postgres: {}