version: '3.7'

x-services-defaults: &defaults
  restart: unless-stopped
  networks:
    - risk-place_ntk
  extra_hosts:
      - "host.docker.internal:172.17.0.1"

services:
  db:
    <<: *defaults
    image: postgres:9.4
    container_name: risk_place_db
    tty: true
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
   
  api:
    <<: *defaults
    container_name: risk_place_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/src/
    ports:
      - "${PORT_SERVER}:${PORT_SERVER}"
    depends_on:
      - db

networks:
  risk-place_ntk: {}

volumes:
  postgres: {}