basePath: /
definitions:
  authjwt.Data:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  authjwt.Token:
    properties:
      token:
        type: string
    type: object
  entities.Auth:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      password:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  entities.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      updated_at:
        type: string
      verificationCode:
        type: string
      verifyEmail:
        type: boolean
    type: object
  rest.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  rest.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  user.CreateUserDTO:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  user.DTO:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      updated_at:
        type: string
    type: object
  user.LoginDTO:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  user.UpdateUserDTO:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  warning_usecase.DTO:
    properties:
      fact:
        type: string
      id:
        type: string
      is_anonymous:
        type: boolean
      is_fake:
        type: boolean
      is_victim:
        type: boolean
      latitude:
        type: number
      longitude:
        type: number
      reported_by:
        type: string
      user:
        $ref: '#/definitions/entities.User'
    type: object
  warning_usecase.UpdateWarningDTO:
    properties:
      fact:
        type: string
      id:
        type: string
      is_anonymous:
        type: boolean
      is_fake:
        type: boolean
      is_victim:
        type: boolean
      latitude:
        type: string
      longitude:
        type: string
      reported_by:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Risk Place Angola server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Risk Place Angola API
  version: 1.0.0
paths:
  /:
    get:
      consumes:
      - application/json
      description: Home page of the API server of Risk Place Angola
      produces:
      - application/json
      responses:
        "200":
          description: Hello, Angola!
          schema:
            type: string
      summary: Home
      tags:
      - Home
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: Find All User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.DTO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Find All User
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user.DTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Create User
      tags:
      - User
  /api/v1/user/{id}:
    delete:
      consumes:
      - application/json
      description: Delete User
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Delete User
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Find User By ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.DTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Find User By ID
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update User
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.UpdateUserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.DTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Update User
      tags:
      - User
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: Login User
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.DTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Login User
      tags:
      - User
  /api/v1/warning:
    get:
      consumes:
      - application/json
      description: Find all warnings
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/warning_usecase.DTO'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Find all warnings
      tags:
      - Warning
    post:
      consumes:
      - application/json
      description: Create a warning
      parameters:
      - description: Reported by
        in: formData
        name: reported_by
        required: true
        type: string
      - description: Latitude
        in: formData
        name: latitude
        required: true
        type: string
      - description: Longitude
        in: formData
        name: longitude
        required: true
        type: string
      - description: Fact
        in: formData
        name: fact
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create a warning
      tags:
      - Warning
  /api/v1/warning/{id}:
    delete:
      consumes:
      - application/json
      description: Remove warning
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Remove warning
      tags:
      - Warning
    get:
      consumes:
      - application/json
      description: Find warning by ID
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/warning_usecase.DTO'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Find warning by ID
      tags:
      - Warning
    put:
      consumes:
      - application/json
      description: Update a warning
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Warning
        in: body
        name: update_warning
        required: true
        schema:
          $ref: '#/definitions/warning_usecase.UpdateWarningDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/warning_usecase.UpdateWarningDTO'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Update a warning
      tags:
      - Warning
  /auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: Auth
        in: body
        name: place
        required: true
        schema:
          $ref: '#/definitions/authjwt.Data'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authjwt.Token'
        "401":
          description: UnAuthorized
          schema:
            type: string
      summary: auth
      tags:
      - Auth
  /authgenerateapi:
    get:
      consumes:
      - application/json
      description: generate api authentication
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: authgenerateapi
      tags:
      - Auth
  /auths:
    get:
      consumes:
      - application/json
      description: return all auths
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Auth'
            type: array
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: auths
      tags:
      - Auth
  /ws:
    get:
      consumes:
      - application/json
      description: websocket url ws://host/ws or use authentication ssl wss://host/ws
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Websocket server
      tags:
      - Websocket
schemes:
- http
swagger: "2.0"
